backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "albums" # 改用相簿的概念
    label: "攝影相簿"
    folder: "_data/albums" # 每個相簿會存成一個獨立檔案，比較好管理
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "小標題 (例如: 2025 S1)", name: "title", widget: "string" }
      - label: "大分類"
        name: "category"
        widget: "select"
        options: ["Life", "Camping", "About", "Travel", "Portrait"] # 這裡定義你的大分類
        default: "Life"
      - { label: "封面照片", name: "cover_image", widget: "image" }
      - label: "相片集"
        name: "photos"
        widget: "list"
        fields:
          - { label: "照片", name: "image", widget: "image" }
          - { label: "說明", name: "caption", widget: "string", required: false }
      - { label: "建立日期", name: "date", widget: "datetime" }
